# Generated by Django 5.1 on 2024-09-03 07:57

from django.db import migrations

def assign_blog_contributor(apps, schema_migration):
    Blog = apps.get_model('blog', 'Blog')
    
    for blog in Blog.objects.all(): 
        blog.contributors.add(blog.author, through_defaults={'contribution': 'Auteur principal'})
    
    
class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_author_blogcontributor_blog_contributors'),
    ]

    operations = [
         migrations.RunPython(assign_blog_contributor)
    ]
